name: "Terraform Cloud AWS Provisioning"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Run Terraform with Terraform Cloud"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Set Terraform Cloud Credentials
        run: |
          export TF_CLOUD_TOKEN=${{ secrets.TF_API_TOKEN }}
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
